name: Deploy to Cloud Run Job

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: rxmz-tech
  FUNCTION_NAME: github-activity-job
  REGION: us-central1
  SERVICE_ACCOUNT_EMAIL: 	github@rxmz-tech.iam.gserviceaccount.com

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:

        workload_identity_provider: 'projects/473421470740/locations/global/workloadIdentityPools/github-activity-job/providers/github-activity-job'
        service_account: ${{ env.SERVICE_ACCOUNT_EMAIL }}

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Get secrets from Secret Manager
      id: get-secret
      run: |
        MANAGEMENT_SECRET=$(gcloud secrets versions access latest --secret="github-notifications" --project=${{ env.PROJECT_ID }})

        echo "$MANAGEMENT_SECRET" > .env

    - name: Print .env contents
      run: |
        echo "Printing .env contents:"
        cat .env

    - name: Deploy to Cloud Run
      run: |
        gcloud run jobs deploy ${{ env.FUNCTION_NAME }} \
            --region=${{ env.REGION }} \
            --image=gcr.io/${{ env.PROJECT_ID }}/${{ env.FUNCTION_NAME }}:latest \
            --task-timeout=300s \ #
            --cpu=1 \
            --memory=1Gi \
            --max-retries=1 \
            --project=${{ env.PROJECT_ID }}